### ISSUE TITLE
Does not work on master

### ISSUE THREAD

**Issue by ruudk** [OskarStark/symfony-cloud-ga#2]
```
Symfony CLI version v4.9.0 (Thu Oct 31 14:47:10 UTC 2019)
Local project linked

Next Steps
----------

 * Deploy: symfony deploy
master
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
fatal: A branch named 'master' already exists.

```

Any ideA?

**Comment by OskarStark** [comment]
Hi @ruudk 

currently it is not working at all, maybe this should be mentioned somewhere in this repo.
The reason is, that we need some support from @tucksaun to get some flags for the `symfony` commands like:

symfony env:create .....  --if-not-exists

currently it fails an will therefore not execute the following `symfony deploy` step

**Comment by ruudk** [comment]
Got it working with this code:
```yaml
name: CI
on: [push]
jobs:
    deploy:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
                with:
                    ref: master
            -   name: Install Symfony CLI
                run: |
                    wget https://get.symfony.com/cli/installer -O - | bash
                    echo ::add-path::$HOME/.symfony/bin
            -   name: Install SSH key
                uses: shimataro/ssh-key-action@v1
                with:
                    private-key: ${{ secrets.SYMFONY_DEPLOY_KEY_PRIVATE }}
                    public-key: ${{ secrets.SYMFONY_DEPLOY_KEY_PUBLIC }}
                    known-hosts: ${{ secrets.SYMFONY_KNOWN_HOSTS }}
            -   uses: webfactory/ssh-agent@v0.2.0
                with:
                    ssh-private-key: ${{ secrets.SYMFONY_DEPLOY_KEY_PRIVATE }}
            -   name: Deploy
                run: |
                    git fetch --prune --unshallow
                    symfony link ${{ secrets.SYMFONY_PROJECT_ID }}
                    symfony version
                    symfony deploy
                env:
                    SYMFONY_ENVIRONMENT: master
                    SYMFONY_TOKEN: ${{ secrets.SYMFONY_TOKEN }}
```

Hope it helps somebody :)
